-- MySQL Script generated by MySQL Workbench
-- Thu Apr 19 17:27:58 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema HPO
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HPO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HPO` DEFAULT CHARACTER SET utf8 ;
USE `HPO` ;

-- -----------------------------------------------------
-- Table `HPO`.`HPO_hp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HPO`.`HPO_hp` (
  `id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `parent` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_HPO_hp_HPO_hp_idx` (`parent` ASC),
  CONSTRAINT `fk_HPO_hp_HPO_hp`
    FOREIGN KEY (`parent`)
    REFERENCES `HPO`.`HPO_hp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HPO`.`HPO_altId`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HPO`.`HPO_altId` (
  `alt` VARCHAR(45) NOT NULL,
  `id` VARCHAR(45) NOT NULL,
  INDEX `fk_HPO_altId_HPO_hp1_idx` (`id` ASC),
  CONSTRAINT `fk_HPO_altId_HPO_hp1`
    FOREIGN KEY (`id`)
    REFERENCES `HPO`.`HPO_hp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HPO`.`HPO_sourceFiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HPO`.`HPO_sourceFiles` (
  `url` VARCHAR(45) NOT NULL,
  `current` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`url`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HPO`.`HPO_diseaseHP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HPO`.`HPO_diseaseHP` (
  `db` VARCHAR(45) NOT NULL,
  `id` VARCHAR(45) NOT NULL,
  `hp` VARCHAR(45) NOT NULL,
  INDEX `fk_HPO_diseaseHp_HPO_hp1_idx` (`hp` ASC),
  CONSTRAINT `fk_HPO_diseaseHp_HPO_hp1`
    FOREIGN KEY (`hp`)
    REFERENCES `HPO`.`HPO_hp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
